### ISSUE TITLE
Low quality augmented text (Spanish)

### ISSUE THREAD

**Issue by ankandrew** [RasaHQ/taipo#29]
I am currently trying out `taipo keyboard augment` with some **Spanish** text, however I am getting a lot of `?` (question marks) (UTF-8) instead of **nearby** keyboard keys. 

**For example**, the original `si! perdón me confundí yo` gets **augmented as** `si! prrdób me donrund? ? yo`. I would expect the character `í` it to be converted to some character in `{Ī, î, į, ï, 8, í, ì}` (press options) or `{u, j, k, l, o}` (nearby keys). I guess this depends a little bit on keyboard layout. Is this expected?

#### Versions:

```
python	=>	Python 3.7.9
taipo	=>	0.0.5
nlpaug	=>	1.1.7
```

#### Run:
```
python -m taipo keyboard augment --seed-aug 42 --lang es data\nlu_test.yml data\nlu_test_aug.yml
```

_Note: I attach here both files, nlu_test and nlu_test_aug, zipped in nlu_files._

### Original

<details>
<summary><b>nlu.yml</b></summary>
<pre><code>version: "2.0"
nlu:
- intent: greet
  examples: |
    - hola
    - buenos días
    - buen día
- intent: goodbye
  examples: |
    - adiós
    - nos vemos mañana
    - chauu bro!
- intent: affirm
  examples: |
    - sisi correcto
    - sisi tenes razón
    - si! perdón me confundí yo
    - si, es así
- intent: deny
  examples: |
    - no es así
    - al final no era así
    - me dijieron lo contrario el otro día
- intent: thanks
  examples: |
    - graciela!
    - uu me salvastee!
    - joya mil gracias!
    - thanks!
- intent: mood_happy
  examples: |
    - ando bien en general
    - joyaa! :), vos?
- intent: out_of_scope
  examples: |
    - ¿como anda tu tio?
    - quiero un equipo roto y viejo
    - estoy enamorado de vos!
</code></pre>
</details>

### Augmented

<details>
<summary><b>nlu_augmented.yml</b></summary>
<pre><code>version: '2.0'
nlu:
- intent: affirm
  examples: |
   - sisi cortectl
   - sosi tenes razón
   - si! prrdób me donrund? ? yo
   - si, es as? ?
- intent: deny
  examples: |
   - no es as? ?
   - al finao no era as? ?
   - me djjueron lo conttsrio el otro d? ? a
- intent: goodbye
  examples: |
   - qdiós
   - nos vfmos ma? ? ana
   - chaui bro!
- intent: greet
  examples: |
   - nola
   - bienos d? ? as
   - vuen d? ? a
- intent: mood_happy
  examples: |
   - ando bien en generqk
   - 'jpyaa! : ), vos?'
- intent: out_of_scope
  examples: |
   - ? ? clmo snda tu tio?
   - quoero un equipo roto y viejo
   - estoy emakorado de vos!
- intent: thanks
  examples: |
   - nracirla!
   - uu me sxldastee!
   - joya mil grsciws!
   - tnanks!
</code></pre>
</details>

[nlu_files.zip](https://github.com/RasaHQ/taipo/files/7144655/nlu_files.zip)

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @TyDunn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koaning** [comment]
Interesting!

I'm using the nlpaug library under the hood, which suggests proper keyboard layouts for different languages. I haven't been able to reproduce your result though. Could you try running the code below? 

```python
import nlpaug.augmenter.char as nac

aug = nac.KeyboardAug(lang="es", include_special_char=False, include_numeric=False, include_upper_case=False)

for i in range(20):
    print(aug.augment("si! perdón me confundí yo"))
```

It contains the standard settings that we use inside of the library.

**Comment by koaning** [comment]
Now that I look at my output, I think I can spot something that the `nlpaug` library omits. Here's 20 variations.

```
si! psrdón me confundí yo
si! lerdón me confundí yo
si! perdón me sonfubdí yo
si! perdón me confkmdí yo
si! perdón me cinfjndí yo
si! perdón me contunví yo
si! perdóg me confundí yo
si! perdón me domfundí yo
si! perdón me donfunfí yo
si! perdón me clmfundí yo
si! perdón me fonfindí yo
si! perdóh me confundí yo
si! lerdón me confundí yo
si! perdón me xonfunxí yo
si! oerdón me confundí yo
si! perdón me xonfhndí yo
si! perdón me contuhdí yo
si! lerdón me confundí yo
si! oerdón me confundí yo
si! peedón me confundí yo
```

I can't help but notice that `nlpaug` doesn't touch the `ó` and `í` characters. This suggest to me that the library may only support the latin characters on an English keyboard. It also doesn't change the short words, but I think that's due to a setting. This is worth diving into. 

@ankandrew, in your experience. Do users type the accents when interacting with one of your assistants? I might imagine that the accents are skipped on a mobile device, but I'll gladly hear it if that's not the case.

**Comment by ankandrew** [comment]
> Interesting!
> 
> I'm using the nlpaug library under the hood, which suggests proper keyboard layouts for different languages. I haven't been able to reproduce your result though. Could you try running the code below?
> 
> ```python
> import nlpaug.augmenter.char as nac
> 
> aug = nac.KeyboardAug(lang="es", include_special_char=False, include_numeric=False, include_upper_case=False)
> 
> for i in range(20):
>     print(aug.augment("si! perdón me confundí yo"))
> ```
> 
> It contains the standard settings that we use inside of the library.

Yep, I see similar results (no weird output). Can this be an export related bug? (Or I may start to think my text editor corrupted the file)



> Now that I look at my output, I think I can spot something that the `nlpaug` library omits. Here's 20 variations.
> 
> ```
> si! psrdón me confundí yo
> si! lerdón me confundí yo
> si! perdón me sonfubdí yo
> si! perdón me confkmdí yo
> si! perdón me cinfjndí yo
> si! perdón me contunví yo
> si! perdóg me confundí yo
> si! perdón me domfundí yo
> si! perdón me donfunfí yo
> si! perdón me clmfundí yo
> si! perdón me fonfindí yo
> si! perdóh me confundí yo
> si! lerdón me confundí yo
> si! perdón me xonfunxí yo
> si! oerdón me confundí yo
> si! perdón me xonfhndí yo
> si! perdón me contuhdí yo
> si! lerdón me confundí yo
> si! oerdón me confundí yo
> si! peedón me confundí yo
> ```
> 
> I can't help but notice that `nlpaug` doesn't touch the `ó` and `í` characters. This suggest to me that the library may only support the latin characters on an English keyboard. It also doesn't change the short words, but I think that's due to a setting. This is worth diving into.
> 
> @ankandrew, in your experience. Do users type the accents when interacting with one of your assistants? I might imagine that the accents are skipped on a mobile device, but I'll gladly hear it if that's not the case.

Yes, I did also notice that characters like `ó` and `í` aren't augmented. For the short words, it seems possible to change that [setting](https://github.com/makcedward/nlpaug/blob/5480074c61978e735f21af165f9ace73e8fa99bd/nlpaug/augmenter/char/keyboard.py#L35).

Well, I guess it really depends, but many times they do include accents when they type.

**Comment by koaning** [comment]
I've tried playing around with the `include_special_char` setting, but this only adds non-alphanumeric characters on the keyboard. It still omits accented characters. 

If you could double-check your text editor that'd be grand. What text editor are you using? Can you instead try to print to stdout in a terminal? Are you using Windows?

**Comment by ankandrew** [comment]
I opened `nlu_test_augmented.yml` (found here: [nlu_files.zip](https://github.com/RasaHQ/taipo/files/7144655/nlu_files.zip)) with Sublime Text (w/ UTF-8 encoding - Windows). Can you visualize properly that file?

 I don't know if it helps, but running when checking file I get weird characters:
```shell
MINGW64 ~/Desktop
$ cat nlu_test_aug.yml
version: '2.0'
nlu:
- intent: affirm
  examples: |
   - sisi cortectl
   - sosi tenes razón
   - si! prrdób me donrund▒ ▒ yo
   - si, es as▒ ▒
   ...
```

**Comment by koaning** [comment]
Then I fear what you're experiencing in part is related to Windows. 

Here's what I see from the terminal. 

```
> python -m taipo keyboard augment --seed-aug 42 nlu_files/nlu_test.yml test.yml
> cat test.yml 
version: '2.0'
nlu:
- intent: affirm
  examples: |
   - sisi cortectl
   - sosi tenes razón
   - si! perdón me ckhfundí yo
   - si, es así
- intent: deny
  examples: |
   - no es así
   - al tinal no era así
   - me dijirdon lo cpntrarjo el otro día
- intent: goodbye
  examples: |
   - qdiós
   - nos vfmos mañana
   - chaui bro!
- intent: greet
  examples: |
   - nola
   - bienos días
   - vuen día
- intent: mood_happy
  examples: |
   - anvo bien en general
   - 'jogaa! : ), vos?'
- intent: out_of_scope
  examples: |
   - ¿ ckmo anda tu tio?
   - quiero un equipo roto y vieko
   - esfoy enamorado de vos!
- intent: thanks
  examples: |
   - grackdla!
   - uu me salbsstee!
   - joyw mil gracias!
   - thankw!
```

**Comment by ankandrew** [comment]
Seeing it a little bit more close, the augmentation from `nlpaug` is **working fine**. The problem is when **reading** the file.

Running:
```python
from taipo.common import nlu_path_to_dataframe
df = nlu_path_to_dataframe("nlu_test.yml")
print(df.head(2))
```

Is where I already get **unexpected** chars:
```shell
  intent          text
0  greet          hola
1  greet  buenos dÃ­as
```

Seems only a Windows problem. Interesting.

**Comment by ankandrew** [comment]
Adding `encoding=utf-8` when reading file in [clump.py](https://github.com/koaning/clumper/blob/578a56ad94998575e3f5337a9c9d21f4e0dd6702/clumper/clump.py#L302) -> `read_yaml` solves my issue. But still don't know why it is only happening on Windows.

Output now:
```shell
  intent         text
0  greet         hola
1  greet  buenos días
```

**Comment by koaning** [comment]
Ah. Grand then we know the issue. 

As luck would have it, I'm also the maintainer of the Clumper repository so I've added a ticket for that [here](https://github.com/koaning/clumper/issues/96). I don't know if I'll be able to get to it today. But hopefully sometime this week.

**Comment by koaning** [comment]
I *just* pushed a new version of Clumper (0.2.15) that should support the encodings while reading csv/yaml.

**Comment by koaning** [comment]
I also *just* updated the requirements for this repository. If you were to reinstall, some of your issues should be gone now.
