### ISSUE TITLE
Mistakes specific OCR 

### ISSUE THREAD

**Issue by MaxHalford** [RasaHQ/taipo#5]
Hey @koaning!

Interesting repo.

I'm currently working a fair bit on correcting OCR mistakes, especially on handwritten text. OCR don't make the same mistakes as humans on keyboard. OCR don't really do any transposition mistakes. It's mostly just characters that are mistaken for another, and spaces that are added.

Do you have any thoughts on this? All the best.

**Comment by koaning** [comment]
This tool is mainly a wrapper around nlpaug for Rasa. It's all meant to work with Rasa so OCR falls outside of scope.

You might want to check out phonetic databank projects though. Besides typos, a lot of spelling errors tend to occur when different spellings sound the same. For the tokenwiser project I've used the jellyfish library for this.
